### ISSUE TITLE
2.21版本网络设置里不能选择使用代理

### ISSUE THREAD

**Issue by dalifeidaop6** [filecxx/FileCentipede#289]
2.21版本，网络设置里，代理设置，只能选择“不使用代理”。
![QQ图片20220710061738](https://user-images.githubusercontent.com/69689662/178124361-078daf52-a853-4baa-befb-81d95cba0891.png)

**Comment by filecxx** [comment]
你点设置菜单时候错过了

![image](https://user-images.githubusercontent.com/100348948/178125393-a163ac15-6287-418d-a638-de2d7dd472f0.png)

**Comment by filecxx** [comment]
Ctrl+Shift+P

**Comment by yichangshengwu** [comment]
> Ctrl+Shift+P

或许，你可以在代理列表里加一个 “添加代理” 的条目？

主要是，大多数软件都把全部设置选项集中在 “设置” 里，
所以大家第一个去找的就是 “设置” 这俩字儿，
两个自带 高亮+加粗+... 的字儿

**Comment by filecxx** [comment]
可以加一个图标按钮在右侧，用于打开代理对话框。

July 18, 2022 10:37:36 PM CEST yich ***@***.***> wrote:

Ctrl+Shift+P
或许，你可以在代理列表里加一个 “添加代理” 的条目？
主要是，大多数软件都把全部设置选项集中在 “设置” 里，
所以大家第一个去找的就是 “设置” 这俩字儿，
两个自带 高亮+加粗+... 的字儿
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
-- Sent with https://mailfence.com  Secure and private email

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/182139150-b447f89c-1bdb-4d0a-bcf9-2937393814cb.png)
已经添加了小图标按钮
