### ISSUE TITLE
无法检查更新；在仪表盘上不能激活软件

### ISSUE THREAD

**Issue by ShoreNinth** [filecxx/FileCentipede#330]
点击检查更新后，状态由“检查中”马上变为“无”。在信息一栏中，检查更新时间与更新时间总是未知，最新版本总是与现版本相同（如果不是进了官网还不知道有新版本）。在仪表盘那里填上软件UID，点击激活后网站直接报error。就算挂代理也不行。

**Comment by filecxx** [comment]
预计下个版本开始启用自动更新功能，仪表盘兑换激活码需要余额或者点卷，否则会提示error.

August 8, 2022 8:32:25 AM CEST "九分邵" ***@***.***> wrote:

点击检查更新后，状态由“检查中”马上变为“无”。在信息一栏中，检查更新时间与更新时间总是未知，最新版本总是与现版本相同（如果不是进了官网还不知道有新版本）。在仪表盘那里填上软件UID，点击激活后网站直接报error。就算挂代理也不行。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Sent with https://mailfence.com  Secure and private email

**Comment by filecxx** [comment]
已经可以自动更新了。
