### ISSUE TITLE
你好，请问软件映射的端口号是多少？

### ISSUE THREAD

**Issue by qdzy9** [filecxx/FileCentipede#439]
我是使用电信送的光猫当路由器拨号的，软件自己没权限映射端口，想手动映射端口但不知道端口号是多少

**Comment by filecxx** [comment]
软件 设置 网络中 默认torrent端口为随机，你可以手动更改。
 

November 17, 2022 at 7:02:15 PM CET qdzy9 ***@***.***> wrote:

我是使用电信送的光猫当路由器拨号的，软件自己没权限映射端口，想手动映射端口但不知道端口号是多少
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Sent with https://mailfence.com  Secure and private email
