### ISSUE TITLE
支持 macOS 吗

### ISSUE THREAD

**Issue by pifeifei** [filecxx/FileCentipede#46]

**Comment by filecxx** [comment]
我没有MacOS的使用经验, 也没有设备, 不过现在软件的代码只需要极少量的修改就可以运行在Mac这类Unix家族的系统上, Mac系统的软件版本现在不是我优先考虑的, 具体添加时间还未知.

**Comment by filecxx** [comment]
我没有MacOS的使用经验, 也没有设备, 不过现在软件的代码只需要极少量的修改就可以运行在Mac这类Unix家族的系统上, Mac系统的软件版本现在不是我优先考虑的, 具体添加时间还未知

March 19, 2022 6:00:06 AM CET "kis龍" ***@***.***> wrote:

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Sent with https://mailfence.com  Secure and private email
