### ISSUE TITLE
Save window position

### ISSUE THREAD

**Issue by smaragdus** [filecxx/FileCentipede#51]
Since version [1.1](https://sourceforge.net/projects/filecentipede/files/1.1/) [File Centipede](http://filecxx.com/en_US/index.html) can save **window size** but the **window position** on desktop is not saved. As a workaround I use an external tool ([SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu)) to position the program window after restart, screen:

![File Centipede 1 4 - 2022-03-22 - 001](https://user-images.githubusercontent.com/9025757/159383046-a8494009-4ea5-49a6-80b9-4211e29c1684.png)

So I suggest that not only window size is saved but also window position on desktop. If this is implemented, the check box may be renamed from:

- **Save window size**

to:

- **Save window state**

as the latter includes both window size and window position.

This is not of great importance but if window position on desktop is saved as well the users would not need to manually adjust the window position after restart.

**Comment by filecxx** [comment]
I am preparing to release 1.5

this option is added

![image](https://user-images.githubusercontent.com/100348948/159388127-e96ebfd9-53bb-4ec9-85b7-c34c20c537fa.png)

(last-modified or date from HTTP headers)
![image](https://user-images.githubusercontent.com/100348948/159388286-34144eaa-a324-4dd7-8585-4de1304ddf84.png)

I prefer a new option "Save window position" instead of replacing "Save window size" to  "Save window state"

thank you very much.

**Comment by smaragdus** [comment]
@filecxx 

Thanks for the quick reply again.

> I prefer a new option "Save window position" instead of replacing "Save window size" to "Save window state"

It is fine.

Also thanks for working on getting files timestamps from server.

Regards

**Comment by stdjs** [comment]
😀sure

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/184495280-9601c367-f8ed-4850-a7b8-aebb55f2018c.png)
Added

**Comment by smaragdus** [comment]
@filecxx 

Thanks!
