### ISSUE TITLE
How to change directory of incomplete save path?

### ISSUE THREAD

**Issue by Terkyz** [filecxx/FileCentipede#633]
Recently I had a strange problem, I was downloading a 200GB file on my 1TB HDD and the SSD where I have Linux installed is only 220GB, in theory I should not have had any problem, but while the file was downloading on the HDD, the storage of my SSD where Linux is installed was getting smaller. 

Here's the funny thing, as soon as I added the file (torrent) to File Centipede, the file automatically appeared in the download path with its full weight on my HDD where it was supposed to be downloaded, and I understand and this is common for example in other download managers that reserve the download space, but the weird thing is that the file as such was taking up space on my SSD, and it got to a point where Plasma notified me that "Not enough space" and my system became completely inoperative. I had to do a forced reboot and the system wouldn't boot from SDDM, so I had to boot from a live session and cd to my SSD and really the weirdest thing is here: When analyzing the space used with a tool called gdu, it appeared that the root directory was not completely flooded, but for some weird reason it was counting the space that was taking up the downloaded file on my hard drive on my SSD, as if /media/ was just another directory, and not where my hard drives are.

I have over 500GB occupied on that hard drive, but specifically that file downloaded with File Centipede was adding space in my root directory.

I suspect it is because "Incomplete save path" points directly to the root directory, and in fact if I didn't change the default download directory my downloads didn't even appear in the root directory, they went to limbo and File Centipede said that "The file had been corrupted or moved".

![filecentipede](https://github.com/filecxx/FileCentipede/assets/102398589/b1913b61-bda7-496d-a4b0-1698e52b835d)

**Comment by filecxx** [comment]
In version 2.82, the feature of "Incomplete save path" has not been implemented and it is a reserved setting.

I use Plasma on an SSD and have mounted an HDD at "/home/xxx/downloads" instead of "/run/media/xxx/A8EE1111111/".
It works flawlessly on my end.

Please note that FileCentipede will only create files in the specified save directory. 
To ensure the accuracy of the "save path", you can use the "edit config" option to check the "save path" is correct.

![image](https://github.com/filecxx/FileCentipede/assets/100348948/ec63e1d2-babd-491d-ad69-6fa040700831)
![image](https://github.com/filecxx/FileCentipede/assets/100348948/4a139eed-aabc-4118-ac2d-bc46d9a4326e)
or
![image](https://github.com/filecxx/FileCentipede/assets/100348948/209a51cc-f1b0-492b-8a75-c1da67bc770c)




Regarding your issue, there could be a few possible causes:

1. The "save path" may not have been set correctly.
2. The HDD may not have been properly mounted (you can check by typing "mount" in the console). See the linked image for an example.
![image](https://github.com/filecxx/FileCentipede/assets/100348948/50c3f0fd-ff6c-42d5-956f-ed949ca31a25)
3. It may be related to filesystem snapshots or journaling.


Note that because FileCentipede uses mmap API to create and write files, if the issue occurs on FileCentipede, it may also occur in other programs. To locate the root of the problem, further testing may be required.

**Comment by Terkyz** [comment]
After two hours burning my brain trying to find some logic to this, I did not come to any conclusion.

After formatting my HDD to make sure, I tried what you said and indeed I have the download pointing to my HDD, but AFTER rebooting my computer the download for some strange reason goes from my HDD to my SSD with the same name as my HDD but with a 1 added at the end.

To demonstrate the problem, I recorded a video before and after:

[Before reboot](https://imgur.com/a/5EalBSb): Here you can see where I add the download and point it to my HDD, and then I show the /media directory to demonstrate that there is indeed no other directory there.

[After reboot](https://imgur.com/a/Ea5mRXF): Adding the fact that my download started from 0, I now have two directories in /media, and if you look closely one has more than 800GB of free space while the other one barely 120GB, and indeed as I mentioned I now have two equal directories but with a 1 at the end, the one that ends in 111 is the one for some reason copied to my main SSD, and the other one was the HDD where I originally started the download.

**Comment by filecxx** [comment]
I'm not sure what's causing this issue since I've never encountered it before. Would you mind trying to mount the /dev/sdd1 on a regular directory like "/home/user/1TB"?

Maybe your computer is haunted.

**Comment by Terkyz** [comment]
Yes, my computer is cursed. I fixed it by doing exactly what you said which was mounting the HDD in /Downloads and funny now the program doesn't open at startup, and I literally haven't touched a single file, the spirit of some ghost punishes me.

**Comment by Terkyz** [comment]
I already found the problem, it seems that FOR SOME REASON if you turn off the PC without pausing the downloads when you restart the PC the downloads will start from 0 from another directory.
